# Generated by Django 3.2.7 on 2021-09-01 15:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/teacher_avatar/')),
                ('description', models.TextField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
