version: '3'

services:
  backend:
    container_name: university
    build: .
    restart: always
    ports:
      - '8002:8000'
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
